---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: system-upgrade-ksm
  namespace: system-upgrade
  labels:
    release: prom-stack
spec:
  endpoints:
    - port: http
      interval: 1m
  namespaceSelector:
    matchNames:
      - system-upgrade
  selector:
    matchLabels:
      app.kubernetes.io/name: system-upgrade-ksm
