apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 10m
  chart:
    spec:
      chart: traefik
      version: 23.x.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  upgrade:
    crds: CreateReplace
  values:
    additionalVolumeMounts:
      - name: access-logs
        mountPath: /var/log/traefik
    deployment:
      additionalContainers:
        - name: access-logger
          image: alpine
          command: ["tail", "-F", "/var/log/traefik/access.log"]
          volumeMounts:
            - name: access-logs
              mountPath: /var/log/traefik
      additionalVolumes:
        - name: access-logs
          emptyDir:
            sizeLimit: 100Mi
    image:
      tag: 2.10.4 # {"$imagepolicy": "flux-system:traefik:tag"}
    logs:
      access:
        enabled: true
        fields:
          headers:
            defaultmode: keep
        filePath: /var/log/traefik/access.log
        filters:
          minduration: 1ms
        format: json
      general:
        format: json
    ports:
      web:
        redirectTo: websecure
