apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: sealed-secrets
      namespace: sealed-secrets
  interval: 10m
  path: ./clusters/k3s/kube-system/sealed-secrets
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
