apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: default
spec:
  interval: 10m
  chart:
    spec:
      chart: podinfo
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: flux-system
      version: 6.x.x
  values:
    ingress:
      enabled: true
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
      hosts:
        - host: podinfo.home.elkiaer.net
          paths:
            - path: /
              pathType: Prefix
      tls:
        - secretName: net-elkiaer-home-podinfo
          hosts:
            - podinfo.home.elkiaer.net
