apiVersion: apps/v1
kind: Deployment
metadata:
  name: speedtest
  namespace: default
spec:
  selector:
    matchLabels:
      app: speedtest
  template:
    metadata:
      labels:
        app: speedtest
    spec:
      containers:
        - name: speedtest
          image: docker.io/miguelndecarvalho/speedtest-exporter:v3.5.4
          ports:
            - name: http
              containerPort: 9798
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL", "NET_RAW"]
            runAsUser: 1001
      securityContext:
        runAsNonRoot: true
