kind: Service
apiVersion: v1
metadata:
  labels:
    app: speedtest
  name: speedtest
  namespace: default
spec:
  selector:
    app: speedtest
  ports:
    - name: http
      port: 9798
      targetPort: 9798
