apiVersion: v1
kind: Deployment
metadata:
  name: speedtest
  namespace: default
spec:
  selector:
    matchLabels:
      app: speedtest
  template:
    spec:
      containers:
        - name: speedtest
          image: docker.io/miguelndecarvalho/speedtest-exporter:v3.5.4
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL", "NET_RAW"]
      securityContext:
        runAsNonRoot: true
