apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  bookmarks.yaml: ""
  services.yaml: |
    - OPNSense:
        icon: opnsense.png
        href: https://opnsense
        description: Router
        widget:
          type: opnsense
          url: https://opnsense
          username: "{{HOMEPAGE_VAR_OPNSENSE_KEY}}"
          password: "{{HOMEPAGE_VAR_OPNSENSE_SECRET}}"
  widgets.yaml: |
    - resources:
        backend: resources
        cpu: true
        disk:
          - /
          - /mnt/data
        expanded: true
        memory: true
        uptime: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
