apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-vars
  namespace: default
spec:
  encryptedData:
    HOMEPAGE_VAR_OPNSENSE_KEY: AgBsEtym0NFg4FA1BO6R/kQpZC0k/sXRZAMsKeeZF7S/EAau9on6THpBhZGp4KCkVatJjfTKfozbKPeVe00srMzXTOVv6uZWKGaC0Z9EW9LxRGNk4r/q/OkUVk9TmfuVTIa5vjkULXZMZlD27Fzemua8JjF0Abn+VpRlQaqBrWAsHT/dAeJ5tbINQHCqCCE+5cvK/2dZ8f2ViR5vUYJ+bVtSyjQvYGeOVvLx37YAGKRbC9yNNaDfl5Dv6+tKfMy2IR7/a/d0FCFWzcPTp0voOqvLgHwG1uD7t0DnwIciIRPwmxS7XBjMNDJrWnXoMAe7seCZwiAX1SYQKgimwfJrwNsj3uATtnYhtpTLcMswz3cgMjebdxZD9V8gJRMOegGXZFtAaISOppXDGUe+RmO7Mf00BkYX2PqRmEW0DaWJWSEArL/tRiUUTaUEZX91o7XIEeGYDEamMVmeksiGUNRixkWpR0xZQjRs3rWeSFizx4DjT4cdnfQi3AI0vbofovRF9qgdYPO01JaLGlj8AvqRBwm8LCX7BGlzTB4wAGFZ3QHOGlmVhqlhCAIEvztaYIO0eoPFlfh0thqa9dHFQmZBhvj2UIgKsqxYvGFI+SS30gTOvLXH8YJteGGi78YKslupQRz7iUY3r4zudvnT820bVKu5/TdSRlCGCiXYQeV4u9s53Mo9fqVwqCxLZUlbkcn514a6vpmYGMenbXuAsSBdhaeBxF1f64VZaDoQm69lpqmNhiO+N0UvJQICfQan21PWCHmgNxzuVYTOy9U2xOwbDGALigbV3amnzK+xV+vO+DOkjA==
    HOMEPAGE_VAR_OPNSENSE_SECRET: AgCiSLUK0lqBjgNMkyy2XyBseQfssoGDDSTs+Z5U7l+xpX3DsMcXYN0j4mwthPfKHMG0n954SgPuUtObTFpJW/woXUFCWeVD5Ezjn/WiJfFlqKYtgs1Y190aoeahoYYRia7fD0hWy2dsygBlYfbheUs3N+/NA4KVeacGTMAGOJwTjxaNFcefWjIrSGWYkhktrQ/fdt5b5MM4/mp+sJIinlFxM85AGnau9KNJQ4pTVj2hefxQcZyMlQw7gaMwoOoG19cBB4uP3vJVTfvd3UWRWwXPcB5lFJQAiPFx84b6LqSR4mVvxwR2XC8F29mswUWLXHHs4aKheV8BDaLvyRBVq2ZRj4Mhy+HLS8z92fDN6GXW4bA0JOKqBRUgeCNTkmVuCXOUy1vlac4EqnyAtvfpTpTuln9Y7Xxi5NoqYW4RNzhRqvF4YdwcN6ogxgibNWFA9VcWJSo/GnT4ODV1i7uoCCwt5e+qwVYEvEtw+CDbA6pEaaEh2KwM028pzl/WgDEcyYYbooQCeFeCkqzd+Ut9KqJUJmcz1K/11k2eGS0sV64YYMpvciBhiRutgxtFig0BL5f4/ZsebPGvn7RP00PxJL6R/KK6v0CTA7oobcPsBOpgCeZufMLOJanfvK3jyO95wx3KJbEAsG4dKpATybeSLCz9f9o/pDnLn6quVjowSVgl5qZDZEBrfFj0sosg6/Z2+6Rwmg5XpBt6jPg41US87xq2E/OFI5RbxK2dD2ielZncN6DNsI/am+YPsr7N7DMJUaUp0+IsUQOiJO5FNirQtOTi0k97qC/CGEjKO9lA/02doA==
  template:
    metadata:
      creationTimestamp: null
      name: homepage-vars
      namespace: default
    type: Opaque

