kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: gluetun
  name: gluetun
spec:
  selector:
    app.kubernetes.io/name: gluetun
  ports:
    - name: control
      port: 8000
      targetPort: control
      protocol: TCP
    - name: shadowsocks-tcp
      port: 8388
      targetPort: shadowsocks-tcp
      protocol: TCP
    - name: shadowsocks-udp
      port: 8388
      targetPort: shadowsocks-udp
      protocol: UDP
