kind: Service
apiVersion: v1
metadata:
  labels:
    app.kubernetes.io/name: speedtest
  name: speedtest
spec:
  selector:
    app.kubernetes.io/name: speedtest
  ports:
    - name: http
      port: 9798
      targetPort: http
