apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: speedtest
spec:
  imageRepositoryRef:
    name: speedtest
    namespace: default
  policy:
    semver:
      range: v3.x.x
