---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: 677ae900-dfbc-41f7-9c41-b45301558d25
