apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: github-token
  namespace: flux-system
spec:
  encryptedData:
    token: AgB79rPSdBmWUfKeRSwJEI6QMpmND52hUibffOx0TfZnM+pVaYBNs8rizpjnTMrl+QdiXjiCvnaIw3QKzhWovVpMc4H5KRMQvHO+TGo+n+b/v+nia0vQWaPAE1scf2oCRpyi9wEkH3lydrjco1Uy93s2BNVd4zTddIDsOScIycX2XiF/nr/TacOPprgLpMoX+6sG9XQ8nnISYFucE6urt9mIIe42+g5pKf8jLLb9S2TBtc6immOyKGPw5RXzl4G123hSpq79a7tU6+ThTlHJTH8I2hHPGCMKC1jV9H6dMujVWe+bQYu1CV71lR6F5iGfGfM6zAGExSPnAzEiiiyFCCs3AemxhbeAyTv45aYYMX0FoqGw846bSWDS4jSCNEA9MHYDLHLCxTiEHbmYo+M/vpLtGWKL/9SpBYCcogdJfWtT2mOvRb2FKMje/TU6vxgOHXX1yFtD1ijPalF5J5TIZ7neUhKlkGt9CCQ4HDc6QPES+W1qkVxGi54Ydj3lJARgF5PYgpC6EvJR8e7g5w8D1rMaa/+eTGkzRZyHnGTVIeFwcjwhCjYre/RiCUNuAz4/d8w7hSv+1FetQVOHpjyRfjf4Iy1GmGxiaMp/WUKInEkuGJjvmpmScI7xf1YrQYsR+JimLGvR6E9beFiYgkwcDuRyznKC/8ShQ4PFHgcf84bOk11r4sa8Jh+EXi/HAeDbTIkwa7ZqIstzEOcU4e/26/+ZeL6BFkP979Sp3v+vplWYvCZkgr4eTAzMFkdzXxayollMM/XCn3X45sLPosXDz4roVElvj4qYGR57tVnQxgJo0PI8S+H2zBo1CKlAcn8=
  template:
    metadata:
      creationTimestamp: null
      name: github-token
      namespace: flux-system

