apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 10m
  path: ./traefik
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: traefik
