apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: octoprint
  name: octoprint
spec:
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    app.kubernetes.io/name: octoprint
