apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: k8up
spec:
  interval: 10m
  chart:
    spec:
      chart: k8up
      version: 4.9.0
      sourceRef:
        kind: HelmRepository
        name: k8up
        namespace: backup
  upgrade:
    crds: CreateReplace
  values:
    k8up:
      skipWithoutAnnotation: true
      envVars:
        - name: BACKUP_GLOBALREPOPASSWORD
          valueFrom:
            secretKeyRef:
              name: restic
              key: password
        - name: BACKUP_GLOBALS3ENDPOINT
          value: https://942d7eb18ddb4433389d1376141361bb.eu.r2.cloudflarestorage.com
        - name: BACKUP_GLOBALS3BUCKET
          value: backup
        - name: BACKUP_GLOBALACCESSKEYID
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: accessKeyID
        - name: BACKUP_GLOBALSECRETACCESSKEY
          valueFrom:
            secretKeyRef:
              name: s3-credentials
              key: accessKeySecret
