---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: restic
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: password
      remoteRef:
        key: d2f0fd6d-af60-44c0-84e0-b453015188c7
