apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: node-red
spec:
  imageRepositoryRef:
    name: node-red
    namespace: home-automation
  policy:
    semver:
      range: 3.x.x
