apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  components:
    - ../../_shared
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: cert-manager
      namespace: cert-manager
  interval: 10m
  path: ./cert-manager/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: cert-manager
