apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default
  namespace: flux-system
spec:
  components:
    - ../_shared
  dependsOn:
    - name: monitoring
  interval: 10m
  path: ./default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: default
