apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: proxy
  namespace: flux-system
spec:
  components:
    - ../_shared
  dependsOn:
    - name: sealed-secrets
  interval: 10m
  path: ./proxy
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: proxy
