apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: system-upgrade-controller
  namespace: flux-system
spec:
  interval: 10m
  path: ./system-upgrade/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: system-upgrade
  wait: true
