apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgALk+P3D8rUSjrfdPViHHwmCpBcfKry6KTM9S1lh72lDmzV1jmx4C2JEWXW6MRNrFNtnh7StQmbe1NY2Jda70ooUmRVNwsJJllXm0uBk2uS6wmrLYj0+sJG8HjlsYiLtKPlaVDBjgTpmjyf0F9bU0DTOaChvYWFjEE3ab/mUjiFZvc0brI7AYnXKbdihVJzxFO6em4QhEkLr6wnYXRDZbwqxe6L7tbnXzQHAQXUsppUSjSVAac6BJGN9xMBcqBa9Q1rPxwQqbB01zHqFD9YOmNKz0NUnaeNVgLdmaOD91SJjwqI5J2NvNYCZP+d+xep7YEz/rVqLW3sZEoy7ZxCSJaTUCJ73zfo/BAqOXAUDh6qcbS3r1p2BsBWn1p31Nlx47UmkS5Ai5DEdZi1bi1pmN4l3X8haUp1bck1bNWM0qiXFqiHwJci4bg5QMBUhEctiLlf/NH9T0LwuT/E8cbceYfZ6nMDNItL+aQMK3pDSYSfKGUyL0tVsBcaGiqRnyEXbnvWBrgr0zylEw714ER5Sg3pRTlvvgFcDIfHQTRKvmkxeH4po60hHFlEPPbD6t94DsFFIiAYTwWkPHCDstWllwjXs/ySn01uwpJoxYaBFlM6u/o2duc+aeQzFtuCkdYzict4J+bT9Onm+36KoWjOISQvV6VUUVZCwoRqPd6ULgwkOEQVLCaiKQtvcWkJfc6DjosFn0+sY9SoboDUMNUjtiJ36KOBdvIyOT99leGiblnjMhw=
  template:
    metadata:
      creationTimestamp: null
      name: hetzner-secret
      namespace: cert-manager
    type: Opaque

