---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: gotify-alertmanager-token
  namespace: monitoring
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: token
      remoteRef:
        key: 21a7c724-80f7-4b75-85fb-b4d90107da4d
