apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: prom-stack
spec:
  interval: 10m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 67.8.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: monitoring
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      grafana.ini:
        auth.anonymous:
          enabled: true
          org_role: Editor
      ingress:
        annotations:
          gethomepage.dev/enabled: "true"
          gethomepage.dev/description: Dashboards and alerts
          gethomepage.dev/group: System
          gethomepage.dev/icon: grafana.png
          gethomepage.dev/name: Grafana
          gethomepage.dev/pod-selector: app.kubernetes.io/name=grafana
          gethomepage.dev/widget.type: "grafana"
          gethomepage.dev/widget.url: "https://grafana.home.elkiaer.net"
          gethomepage.dev/widget.username: '{{`{{HOMEPAGE_VAR_GRAFANA_USERNAME}}`}}'
          gethomepage.dev/widget.password: '{{`{{HOMEPAGE_VAR_GRAFANA_PASSWORD}}`}}'
        enabled: true
        hosts:
          - grafana.home.elkiaer.net
      sidecar:
        dashboards:
          labelValue: "1"
          searchNamespace: "ALL"
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
