apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cert-manager-webhook-hetzner
spec:
  interval: 10m
  chart:
    spec:
      chart: cert-manager-webhook-hetzner
      version: 1.3.0
      sourceRef:
        kind: HelmRepository
        name: cert-manager-webhook-hetzner
        namespace: cert-manager
  dependsOn:
    - name: cert-manager
  upgrade:
    crds: CreateReplace
  values:
    groupName: elkiaer.net
