apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: cert-manager-webhook-hetzner
  namespace: cert-manager
spec:
  interval: 10m0s
  url: https://vadimkim.github.io/cert-manager-webhook-hetzner

