apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: net-elkiaer
spec:
  commonName: "elkiaer.net"
  dnsNames:
    - elkiaer.net
    - "*.elkiaer.net"
    - "*.home.elkiaer.net"
  issuerRef:
    name: letsencrypt
    kind: ClusterIssuer
  secretName: net-elkiaer
