kind: Service
apiVersion: v1
metadata:
  labels:
    app: traefik
  name: traefik-api
spec:
  selector:
    app.kubernetes.io/instance: traefik-traefik
    app.kubernetes.io/name: traefik
  ports:
    - name: traefik
      port: 9000
      targetPort: traefik
