apiVersion: v1
kind: Service
metadata:
  name: traefik-test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - name: web
      port: 80
      targetPort: web
      nodePort: 30007
    - name: websecure
      port: 443
      targetPort: websecure
      nodePort: 30008
