apiVersion: v1
kind: Service
metadata:
  name: traefik-test
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: traefik
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
    - port: 443
      targetPort: 443
      nodePort: 30008
