---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: bitwarden-sdk-tls
  namespace: kube-system
spec:
  secretName: bitwarden-sdk-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  dnsNames:
    - external-secrets-bitwarden-sdk-server
    - external-secrets-bitwarden-sdk-server.kube-system
    - external-secrets-bitwarden-sdk-server.kube-system.svc.cluster.local
  issuerRef:
    name: bitwarden-selfsigned-issuer
    kind: Issuer
    group: cert-manager.io
