---
apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://bitwarden-sdk-server.kube-system.svc.cluster.local:9998
      caProvider:
        type: Secret
        # TODO: Set up trust-manager in order to use separate CA certificate secret
        # - see: https://cert-manager.io/docs/trust/trust-manager/
        name: bitwarden-tls-certs
        key: ca.crt
        namespace: kube-system
      auth:
        secretRef:
          credentials:
            name: bitwarden-sm-token
            key: token
            namespace: kube-system
      organizationID: 172335ba-a896-4f5e-a70b-b264014ba18a
      projectID: 31694c07-2473-45e1-bd91-b27000c93c02
