---
apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: bitwarden-secrets-manager
spec:
  provider:
    bitwardensecretsmanager:
      bitwardenServerSDKURL: https://external-secrets-bitwarden-sdk-server.kube-system.svc.cluster.local:9998
      caProvider:
        type: Secret
        name: bitwarden-sdk-tls
        key: ca.crt
        namespace: kube-system
      auth:
        secretRef:
          credentials:
            name: bitwarden-sm-token
            key: token
            namespace: kube-system
      organizationID: 172335ba-a896-4f5e-a70b-b264014ba18a
      projectID: 31694c07-2473-45e1-bd91-b27000c93c02
