apiVersion: k8up.io/v1
kind: Schedule
metadata:
  name: home-automation-daily
spec:
  backup:
    schedule: "0 5 * * *"  # Runs at 5:00 AM every day*/5 * * * *'
    failedJobsHistoryLimit: 2
    successfulJobsHistoryLimit: 2
