apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: zigbee2mqtt
spec:
  imageRepositoryRef:
    name: zigbee2mqtt
    namespace: home-automation
  policy:
    semver:
      range: 1.x.x
