apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  image: docker.io/bitnami/sealed-secrets-controller
  interval: 10m0s
