apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: traefik
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: traefik
  policy:
    semver:
      range: v2.x.x
