apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: default
  namespace: flux-system
spec:
  dependsOn:
    - name: monitoring
  interval: 10m
  path: ./clusters/k3s/default
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
