apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-automation
  namespace: flux-system
spec:
  interval: 10m
  path: ./clusters/k3s/home-automation
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
