apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metallb-system-controller
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2beta1
      kind: HelmRelease
      name: metallb
      namespace: metallb-system
  interval: 10m
  path: ./clusters/k3s/metallb-system/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
