apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: mosquitto
spec:
  imageRepositoryRef:
    name: mosquitto
    namespace: home-automation
  policy:
    semver:
      range: 2.x
