---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  serviceAccountName: system-upgrade
  upgrade:
    envs:
      - name: SYSTEM_UPGRADE_K3S_STATE_DIR
        value: /home/me/.rancher/k3s
    image: rancher/k3s-upgrade@sha256:f523c4ab1c5654b6430335b049470fb8d9afb4434963ada34f011bfb6d62d18a
  version: v1.37.0+k3s1
