---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  serviceAccountName: system-upgrade
  upgrade:
    envs:
      - name: SYSTEM_UPGRADE_K3S_STATE_DIR
        value: /home/me/.rancher/k3s
    image: rancher/k3s-upgrade@sha256:20d6f22e7383bead1a48ad0838247080c5d5b28ac0f10dd2348ebe0a5466a043
  version: v1.36.3+k3s1
