---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: server
spec:
  concurrency: 1
  cordon: true
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: In
        values:
          - "true"
  serviceAccountName: system-upgrade
  upgrade:
    envs:
      - name: SYSTEM_UPGRADE_K3S_STATE_DIR
        value: /home/me/.rancher/k3s
    image: rancher/k3s-upgrade@sha256:93052df228bab0ad56df1fd1591e56f526993a6b2ca2f1c4cf42626f70ad0a27
  version: v1.36.3+k3s1
