apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sealed-secrets
spec:
  imageRepositoryRef:
    name: sealed-secrets
    namespace: kube-system
  policy:
    semver:
      range: <1.0.0
