apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
spec:
  interval: 10m
  chart:
    spec:
      chart: sealed-secrets
      version: 2.17.0
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets
        namespace: kube-system
  upgrade:
    crds: CreateReplace
  values:
    fullnameOverride: sealed-secrets-controller
    image:
      tag: 0.24.5 # {"$imagepolicy": "kube-system:sealed-secrets:tag"}