apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: prom-stack
  namespace: monitoring
spec:
  interval: 10m0s
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 48.x.x
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  upgrade:
    crds: CreateReplace
  values:
    grafana:
      ingress:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: letsencrypt
        hosts:
          - grafana.home.elkiaer.net
        tls:
          - secretName: net-elkiaer-home-grafana
            hosts:
              - grafana.home.elkiaer.net
    prometheus:
      prometheusSpec:
        storageSpec:
          volumeClaimTemplate:
            spec:
              accessModes: ["ReadWriteOnce"]
              resources:
                requests:
                  storage: 20Gi
