---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: s3-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: accessKeyID
      remoteRef:
        key: d627aa29-ca29-4805-af62-b45300c34b8e
    - secretKey: accessKeySecret
      remoteRef:
        key: 6adbd149-4081-4489-9170-b45300c46eeb
