apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: homeassistant
  annotations:
    gethomepage.dev/enabled: "true"
    gethomepage.dev/description: Home devices, automations, and dashboards
    gethomepage.dev/group: Home Automation
    gethomepage.dev/icon: homeassistant.png
    gethomepage.dev/name: Home Assistant
    gethomepage.dev/widget.type: "homeassistant"
    gethomepage.dev/widget.url: "https://ha.home.elkiaer.net"
    gethomepage.dev/widget.key: "{{HOMEPAGE_VAR_HOMEASSISTANT_TOKEN}}"
spec:
  rules:
    - host: ha.home.elkiaer.net
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: homeassistant
                port:
                  name: http
