apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: external-secrets
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: kube-system
  install:
    crds: CreateReplace
  upgrade:
    crds: CreateReplace
  values:
    installCRDs: true
    bitwarden-sdk-server:
      enabled: true
      # This secret will be created by cert-manager
      extraVolumes:
        - name: tls
          secret:
            optional: true
            secretName: bitwarden-sdk-tls
      extraVolumeMounts:
        - name: tls
          mountPath: /etc/external-secrets/tls
          readOnly: true
      env:
        - name: BITWARDEN_SDK_SERVER_CERT_PATH
          value: /etc/external-secrets/tls/tls.crt
        - name: BITWARDEN_SDK_SERVER_KEY_PATH
          value: /etc/external-secrets/tls/tls.key

