apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gluetun
  name: gluetun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gluetun
  template:
    metadata:
      labels:
        app: gluetun
    spec:
      containers:
        - name: gluetun
          env:
            - name: SHADOWSOCKS
              value: on
          envFrom:
            - secretRef:
                name: wireguard-config
          image: qmcgaw/gluetun:v3.35.0
          ports:
            - name: shadowsocks-tcp
              containerPort: 8388
              protocol: TCP
            - name: shadowsocks-udp
              containerPort: 8388
              protocol: UDP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              add: ["NET_ADMIN", "SYS_MODULE"]
              drop: ["ALL", "NET_RAW"]
            runAsUser: 1001
      securityContext:
        runAsNonRoot: true
