apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: sealed-secrets
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: sealed-secrets
  policy:
    semver:
      range: <1.0.0
