---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dagger
spec:
  interval: 1m0s
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.21.7
    digest: sha256:a4e391c8fc528e2bc7377ef1010c63dcf7c4779904ed131f4ca37a64eb6d7842
  url: oci://registry.dagger.io/dagger-helm
