---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagger
spec:
  chart:
    spec:
      chart: dagger
      interval: 1m0s
      version: 0.14.0
      sourceRef:
        kind: HelmRepository
        name: dagger
  interval: 1m0s
