---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dagger
spec:
  interval: 1m0s
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.21.0@sha256:f2f8e06ea24fd40d16633fdece548f2fbee87020a558965d1ffd54a2ad4ffc65
  url: oci://registry.dagger.io/dagger-helm
