---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dagger
spec:
  interval: 1m0s
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.19.8@sha256:197a309ac3015a52ceff4dfe93bd43d3a4570a9894c8957105d2065ae7455a5c
  url: oci://registry.dagger.io/dagger-helm
