---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dagger
spec:
  chartRef:
    kind: OCIRepository
    name: dagger
  interval: 1m0s
  postRenderers:
    - kustomize:
        patches:
          - target:
              kind: DaemonSet
            # TODO: Remove workaround once fixed in chart
            # - details here: https://github.com/fluxcd/flux2/issues/4910#issuecomment-2286684282
            patch: |
              - op: replace
                path: /metadata/labels/app.kubernetes.io~1version
                value: latest
              - op: replace
                path: /spec/template/metadata/labels/app.kubernetes.io~1version
                value: latest
