---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dagger
spec:
  interval: 1m0s
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.19.6@sha256:895986dd013a72ae2d9cb248405741115199aef48d73dabebf91552e39e84acc
  url: oci://registry.dagger.io/dagger-helm
