---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dagger
spec:
  interval: 1m0s
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.15.3@sha256:717367ad47626f66e7faf19ab656a21b32d82c3d94c6e34ddf8596dc9dc2fa40
  url: oci://registry.dagger.io/dagger-helm
