---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: dagger
spec:
  interval: 1m0s
  layerSelector:
    mediaType: "application/vnd.cncf.helm.chart.content.v1.tar+gzip"
    operation: copy
  ref:
    tag: 0.20.3@sha256:956d731a72a5046a5bb88a9eea506bf8124f922cc85979800cec400347c26aa7
  url: oci://registry.dagger.io/dagger-helm
