---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: dagger
spec:
  interval: 1m0s
  provider: generic
  ref:
    tag: 0.14.0
  url: oci://registry.dagger.io/dagger-helm
