apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: prom-stack
  name: checkupdates
spec:
  endpoints:
    - interval: 5m
      port: http
      scrapeTimeout: 1m
  namespaceSelector:
    matchNames:
      - default
  selector:
    matchLabels:
      app: checkupdates
