apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: checkupdates
  name: checkupdates
spec:
  selector:
    matchLabels:
      app: checkupdates
  template:
    metadata:
      labels:
        app: checkupdates
    spec:
      containers:
        - name: checkupdates
          image: ghcr.io/mikaelelkiaer/checkupdates-exporter:2.0.0 # {"$imagepolicy": "default:checkupdates"}
          ports:
            - name: http
              containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL", "NET_RAW"]
            runAsUser: 1001
          volumeMounts:
            - mountPath: /tmp/checkupdates.txt
              name: checkupdates-file
              readOnly: true
      securityContext:
        runAsNonRoot: true
      volumes:
        - name: checkupdates-file
          hostPath:
            path: /home/me/checkupdates.txt
            type: File
