---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
    - secretKey: opnsense-key
      remoteRef:
        key: 32258b40-5b2e-4a4b-b682-b45300bba75e
    - secretKey: opnsense-secret
      remoteRef:
        key: 4e67bb70-c4ed-4e41-83d3-b45300bbd31b
