apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: ""
  bookmarks.yaml: ""
  services.yaml: |
    - System:
      - OPNSense:
          icon: opnsense.png
          href: https://opnsense.localdomain
          description: Router
          widget:
            type: opnsense
            url: https://opnsense.localdomain
            username: "{{HOMEPAGE_VAR_OPNSENSE_KEY}}"
            password: "{{HOMEPAGE_VAR_OPNSENSE_SECRET}}"
            wan: opt1
  widgets.yaml: |
    - resources:
        backend: resources
        cpu: true
        disk:
          - /
          - /mnt/data
        expanded: true
        memory: true
        uptime: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
