---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hetzner-secret
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: bitwarden-secrets-manager
    kind: ClusterSecretStore
  data:
  - secretKey: api-key
    remoteRef:
      key: 9c39cbcf-30a1-413f-b908-b45300bb2587
