---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: hetzner-secret
  namespace: cert-manager
spec:
  encryptedData:
    api-key: AgDII1r3sWbRe13EgEv+MUxeTquiE8ZFH6r07LqbTcchRUDP41ev1+ayUQ8j8+BfvckB/zVSkIuVpd65i6In3u6hpoJhoi93pMRGqMCkMcNTshGIoNaaami9SxHcpRqi1FW0jguJIjX4hBaAi7EfRW6EBSdScypOll8mxTb3PoN9UCIf8AqN0OHw8pm68oWxXaZyl5ZOkvAET67CjpVwXsTalt2lXJuZvPqA/UktzkcSezB3s2IA9SBIK/Or7GA06SJT2iptL/8wwx1EYnSLV3ktPOnCW0Q7Qxg7y9PHQ+JxEFLOSje/0BsstCCxJVSZRH7Dz0NyYn6WKuC27Y94BSTYYCkMWYkRT5zoBh3bgb7EC4QopXTyoU4S3LiiWf6yhYlYrfoscncoMrRXL8+wfc944MTS/hVVC2h4PqUungbOZBReScp50PdOiBjIvq91Mr/6sN/AAQlhjFQ81dvzpu579b4RzrewuexDl6qN6cs4KdBxKQSTX3jBNGd0TZh0rOleUq++hJG6HWGaKXyv7yfb63KIFopgKGgYloI7lDP3FyZUaDB5pkLsccQ5MEtuOaQsPX5TTFi0Q+cohJmwtpJ2Ybuq1gNqQB5Zwk1RKlK/fnvRm2nZMnYKdWUr1/jUO7kR/8D8JUvXFX7lnSCYD5dwTDlS7W+wA7vF2Q6D8xKB6u1zS6t3Ie9V8ZyLIvvWik5t/fmKP1ICbpBtRbqPM7V7jk7QKWrumCLmtVzmHv1Ps0c=
  template:
    metadata:
      creationTimestamp: null
      name: hetzner-secret
      namespace: cert-manager
    type: Opaque
