apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-certs
  namespace: flux-system
spec:
  dependsOn:
    - cert-manager-controller
    - sealed-secrets
  interval: 10m
  path: ./cert-manager/certs
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
