apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager-controller
  namespace: flux-system
spec:
  healthChecks:
    - apiVersion: apps/v1
      kind: Deployment
      name: cert-manager
      namespace: cert-manager
  interval: 10m
  path: ./clusters/k3s/cert-manager/controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
