---
apiVersion: k8up.io/v1
kind: Backup
metadata:
  name: backup
spec:
  failedJobsHistoryLimit: 2
  successfulJobsHistoryLimit: 2
  backend:
    s3:
      endpoint: https://942d7eb18ddb4433389d1376141361bb.eu.r2.cloudflarestorage.com
      bucket: backup
      accessKeyIDSecretRef:
        name: s3-credentials
        key: accessKeyID
      secretAccessKeySecretRef:
        name: s3-credentials
        key: accessKeySecret
