apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: emqx
  namespace: home-automation
spec:
  interval: 10m
  chart:
    spec:
      chart: helm
      version: 5.x.x
      sourceRef:
        kind: HelmRepository
        name: emqx
        namespace: flux-system
